function [junk] = lap(junk)

% Dummy function that will be called if the function lap.cpp was not
% mex-compiled yet (m-files are called only if a mex file does not
% exist). 
message = sprintf(['*********************************READ ME**********************************\n'...
    'This is the first time that you run GLMD_Demo program.\n'...
    'C++ CODE lap.cpp which contains a solver for the linear assignment problem has NOT yet been complied!\n'...
    'The program will help you to compile this code automatically.\n\n\n'... 
    'Trying to compiling lap.cpp.....................................\n'...
    'Done! \n'...
    'Please restart Matlab and run the GLMD_Demo.m for starting the Demo!\n\n'...
    'Click "Ok" botton for closing Matlab\n'... 
    ]);
mex src\lap.cpp;
uiwait(msgbox(message));
quit;


